### ISSUE TITLE
Example does not run

### ISSUE THREAD

**Issue by bobmayo56** [pofider/node-simple-odata-server#7]
Hi,

I'm trying to get the "Get Started" example to work.  After correcting the package name, the code runs but accessing "http://localhost:1337/$metadata" results in:

```json
{
  "error": {
    "code": 500,
    "message": "Missing attribute value for attribute EntityType of element EntitySet",
    "stack": "Error: Missing attribute value for attribute EntityType of element EntitySet\n    
at new XMLAttribute (\/Users\/bobmayo56\/Documents\/MayoPrivate\/proj\/kkbobquery\/web\/node_modules\/simple-odata-server\/node_modules\/xmlbuilder\/lib\/XMLAttribute.js:14:15)\n    
at XMLElement.module.exports.XMLElement.attribute (\/Users\/bobmayo56\/Documents\/MayoPrivate\/proj\/kkbobquery\/web\/node_modules\/simple-odata-server\/node_modules\/xmlbuilder\/lib\/XMLElement.js:82:35)\n    
at XMLElement.module.exports.XMLNode.element (\/Users\/bobmayo56\/Documents\/MayoPrivate\/proj\/kkbobquery\/web\/node_modules\/simple-odata-server\/node_modules\/xmlbuilder\/lib\/XMLNode.js:79:30)\n    
at XMLElement.module.exports.XMLNode.element (\/Users\/bobmayo56\/Documents\/MayoPrivate\/proj\/kkbobquery\/web\/node_modules\/simple-odata-server\/node_modules\/xmlbuilder\/lib\/XMLNode.js:87:25)\n    
at XMLElement.module.exports.XMLNode.element (\/Users\/bobmayo56\/Documents\/MayoPrivate\/proj\/kkbobquery\/web\/node_modules\/simple-odata-server\/node_modules\/xmlbuilder\/lib\/XMLNode.js:64:28)\n    
at XMLElement.module.exports.XMLNode.element (\/Users\/bobmayo56\/Documents\/MayoPrivate\/proj\/kkbobquery\/web\/node_modules\/simple-odata-server\/node_modules\/xmlbuilder\/lib\/XMLNode.js:84:32)\n    
at XMLElement.module.exports.XMLNode.element (\/Users\/bobmayo56\/Documents\/MayoPrivate\/proj\/kkbobquery\/web\/node_modules\/simple-odata-server\/node_modules\/xmlbuilder\/lib\/XMLNode.js:87:25)\n    
at XMLElement.module.exports.XMLNode.element (\/Users\/bobmayo56\/Documents\/MayoPrivate\/proj\/kkbobquery\/web\/node_modules\/simple-odata-server\/node_modules\/xmlbuilder\/lib\/XMLNode.js:64:28)\n    
at XMLElement.module.exports.XMLNode.element (\/Users\/bobmayo56\/Documents\/MayoPrivate\/proj\/kkbobquery\/web\/node_modules\/simple-odata-server\/node_modules\/xmlbuilder\/lib\/XMLNode.js:84:32)\n    
at XMLElement.module.exports.XMLNode.element (\/Users\/bobmayo56\/Documents\/MayoPrivate\/proj\/kkbobquery\/web\/node_modules\/simple-odata-server\/node_modules\/xmlbuilder\/lib\/XMLNode.js:87:25)",
    "target": "\/$metadata",
    "details": [
      
    ]
  },
  "innererror": {
    
  }
}
```

**Comment by pofider** [comment]
Thanks for pointing it out.

I have fixed get started section in the readme. Please try it again.

**Comment by bobmayo56** [comment]
got it, thanks.
